containers:
    - name: dev-nitrotype-tracker-be-fetch-1
      networks:
        - tyr-infrastructure-internal
        - dev-nitrotype-tracker_internet
        - dev-nitrotype-tracker-local-internal
    - name: dev-nitrotype-tracker-be-fetch-2
      networks:
        - tyr-infrastructure-internal
        - dev-nitrotype-tracker_internet
        - dev-nitrotype-tracker-local-internal
    - name: dev-nitrotype-tracker-be-fetch-3
      networks:
        - tyr-infrastructure-internal
        - dev-nitrotype-tracker_internet
        - dev-nitrotype-tracker-local-internal
    - name: dev-nitrotype-tracker-be-fetch-4
      networks:
        - dev-nitrotype-tracker_internet
        - dev-nitrotype-tracker-local-internal
        - tyr-infrastructure-internal
    - name: dev-nitrotype-tracker-be-fetch-5
      networks:
        - tyr-infrastructure-internal
        - dev-nitrotype-tracker_internet
        - dev-nitrotype-tracker-local-internal
    - name: dev-nitrotype-tracker-postgres
      networks:
        - dev-nitrotype-tracker-local-internal
        - tyr-administration-internal
        - dev-nitrotype-tracker_internet
    - name: dev-nitrotype-tracker-cache
      networks:
        - tyr-administration-internal
        - dev-nitrotype-tracker_internet
        - dev-nitrotype-tracker-local-internal
    - name: dev-nitrotype-tracker-web-1
      networks:
        - tyr-proxy-internal
    - name: dev-nitrotype-tracker-web-2
      networks:
        - tyr-proxy-internal
    - name: dev-nitrotype-tracker-web-3
      networks:
        - tyr-proxy-internal
    - name: dev-nitrotype-tracker-doneman
      networks:
        - dev-nitrotype-tracker_default
    - name: dev-nitrotype-tracker-api
      networks:
        - dev-nitrotype-tracker-local-internal
        - tyr-proxy-internal
        - tyr-infrastructure-internal
